### ISSUE TITLE
Add a mechanism for generating files in the repo

### ISSUE THREAD

**Issue by thufschmitt** [nickel-lang/organist#144]
Add a `files` field to the toplevel Nickel schema for defining files that should be generated in-place in the repo.

For instance:

```
{
  files.myConfigFile = {
    destination = "myConfigFile", # optional, defaults to the name of the field
    content.text = m%"
      foo = 1,
      bar = "baz"
    "%,
  },
}
```

This could be triggered by calling a specific `app` in the flake (`nix run .#organist regenerate` or something like that).

Eventually, this could also replace the current `regenerate-lock-file` logic

**Comment by YorikSar** [comment]
What would be the use case for `destination` field? You can specify anything in the name, can't you?

**Comment by thufschmitt** [comment]
Yes, that's mostly for overriding purposes. If for some reason you want to change the target, you can override the `destination` field (while overriding the field name isn't really possible). Random example of such a thing from my past self: https://github.com/nix-community/home-manager/issues/2360#issuecomment-1009723929
