### ISSUE TITLE
when added as packages in a shell, pkg-config doesn't find packages

### ISSUE THREAD

**Issue by jneem** [nickel-lang/organist#173]
With the `project.ncl` below, if I enter the shell and type `pkg-config --cflags openssl`, it complains that "Package openssl was not found in the pkg-config search path."

```nickel
let inputs = import "./nickel.lock.ncl" in
let organist = inputs.organist in

{
  shells = organist.shells.Bash,

  shells.build = {
    packages = {},
  },

  shells.dev = {
    packages.openssl = organist.import_nix "nixpkgs#openssl",
    packages.pkg-config = organist.import_nix "nixpkgs#pkg-config",
  },
}
  | organist.OrganistExpression
```

**Comment by jmou** [comment]
I am still running into the same problem while trying to get started with Organist. My flake.lock is on the latest commit of the organist repo (19b1dfc5955492fff6109b87f97f4a25d7d7c311) so it includes #174.
