### ISSUE TITLE
How to track old files not generated with Nickel alongside new Nickel-generated files?

### ISSUE THREAD

**Issue by HariAmoor-professional** [nickel-lang/organist#183]
My organization needs to maintain a Helm repo, alongside some Pulumi YAML, in our configuration. We'd like to autogenerate everything with Nix and Nickel, but I'm trying to understand how to import an existing YAML file into Nickel (given Nix store path) and deserialize it to play around with in the language.

Is there some solution for this either in Nickel stdlib or organist?

**Comment by YorikSar** [comment]
You can import existing YAML directly into Nickel with `import` statement, see section “Export & Import” in https://nickel-lang.org/getting-started.

**Comment by HariAmoor-professional** [comment]
Exactly what I need, thanks!

**Comment by yannham** [comment]
Re-reading the getting started page, I just realized it's not up to date with the latest CLI syntax, just so you know! Going to fix that right away.
