### ISSUE TITLE
Comparison to home manager

### ISSUE THREAD

**Issue by ShalokShalom** [nickel-lang/organist#193]
Can I use this on a Linux distribution, that is not NixOS, as a home manager replacement?

Specifically in order to install and organize the Nix packages?

In a declarative way?

**Comment by thufschmitt** [comment]
This is not a home-manager replacement, it isn't meant to handle dotfiles and user configuration. It is meant as a development environment management, so in the same vein as a plain `nix-shell`/`nix develop`, [devenv](https://devenv.sh) or [devbox](https://www.jetpack.io/devbox).

It _could_ be used in such a way (by adding something like `. <(nix print-dev $PATH_TO_CONFIG_REPO)` to `.profile`), but I wouldn't advise it

**Comment by ShalokShalom** [comment]
But since the whole range of packages are available, could I also use it as package source for other distributions?
